CREATE TABLE PLAYERS
(
  PLAYER_ID 	INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME 	VARCHAR(50) NOT NULL,
  LAST_NAME 	VARCHAR(50) NOT NULL,
  DOB 			DATE,
  FANFOOTY_PID	INT,
  PRIMARY KEY 	(PLAYER_ID)
);