CREATE TABLE SC_TEAMS
(
  SC_COACH_ID 		INT NOT NULL,
  SEASON 			INT NOT NULL,
  SC_TEAM_NAME 		VARCHAR(18) NOT NULL,
  FINAL_POSITION 	INT,
  PRIMARY KEY 		(SEASON, SC_COACH_ID),
  FOREIGN KEY 		(SC_COACH_ID) REFERENCES SC_COACHES(SC_COACH_ID)
);

INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (1,2018,"Vodka Kreuzers");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (2,2018,"Post MaSloane");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (3,2018,"The Lyons King");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (4,2018,"Danger Things");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (5,2018,"Since U Been Gawn");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (6,2018,"Crippstocurrency");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (7,2018,"VlastuinTrnslation");
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME) VALUES (8,2018,"Ward of the Rings");

INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (1,2017,"Tuohy's Extra Dry",6); 
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (2,2017,"Absolute Steins",4);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (3,2017,"Wholesome Beams",3);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (4,2017,"Show Me The Mundy",1);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (5,2017,"Free Tibont",7);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (6,2017,"TitchDntKillMyVibe",2);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (7,2017,"Libba Let Die",8);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (8,2017,"I Dream of Viney",5);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (1,2016,"We're Not Gwilty",4);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (2,2016,"Steele Rebuilding",6);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (3,2016,"Brave Hartung",3);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (4,2016,"Such is Fyfe",5);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (5,2016,"Bontback Mountain",1);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (6,2016,"Cotch Me If Ya Can",8);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (7,2016,"Gawn Girl",2);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (8,2016,"Game of Jones",7);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (1,2015,"Winderlich'in Good",7);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (2,2015,"GraysGoneWild",4);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (3,2015,"Agents of SHIELS",5);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (4,2015,"GriffenMeGrief",2);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (5,2015,"PursuitOfChapyness",1);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (6,2015,"Breaking Saad",6);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (7,2015,"SingingInTheRaines",3);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (8,2015,"Praise be to Roos",8);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (1,2014,"Kommer Get It",7);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (2,2014,"Define Collusion",2);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (3,2014,"Lord Spang",6);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (4,2014,"The East Remembers",8);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (5,2014,"Selwooden Beams",3);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (6,2014,"UnShaw",4);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (7,2014,"GoodesWillHunting",1);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (8,2014,"Roos gonna save us",5);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (1,2013,"The McGibblets",7);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (2,2013,"laStarz",3);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (3,2013,"Delicious Rioli",6);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (4,2013,"Eastside Peasants",5);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (6,2013,"Voose Lagina",4);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (7,2013,"Manchesthair UTD",1);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (8,2013,"PeteTopKevinBottom",2);
INSERT INTO SC_TEAMS (SC_COACH_ID,SEASON,SC_TEAM_NAME,FINAL_POSITION) VALUES (9,2013,"passwerrD is Taco",8);
